# Generated by Django 5.0 on 2023-12-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0003_usermeeting_transaksi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMentor',
        ),
    ]
