# Generated by Django 5.0 on 2023-12-30 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_teacher_pendapatan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMentored', models.BooleanField(default=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('like', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=224)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
