# Generated by Django 5.0 on 2023-12-30 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0004_delete_usermentor'),
        ('transaksi', '0002_rename_purchased_transaksi_terbayar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='langganan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Langganan', to='kelas.langganan'),
        ),
    ]
